openapi: 3.0.3
info:
  title: Recipe Recommendation API - Computação na Nuvem
  description: API for searching and recommending recipes based on ingredients and directions.
  version: 1.0.0

servers:
  - url: http://33.XX.XX.XX

paths:
  /:
    get:
      summary: Readiness check
      description: Endpoint to check if the service is ready.
      responses:
        '200':
          description: Service is ready
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ready

  /health:
    get:
      summary: Health check
      description: Endpoint to check if the service is healthy.
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy

  /recommend:
    post:
      summary: Recommend recipes based on a given recipe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe'
            examples:
              carrotCake:
                summary: Carrot Cake Recipe
                value:
                  NER:
                    - oil
                    - sugar
                    - baking soda
                    - cinnamon
                    - eggs
                    - flour
                    - salt
                  directions:
                    - Mix all together.
                    - Bake at 350° for 35 to 45 minutes in a 9 x 13-inch pan.
                  ingredients:
                    - 2 c. flour
                    - 2 c. sugar
                    - 1 tsp. salt
                    - 2 tsp. cinnamon
                    - 2 tsp. baking soda
                    - 1 c. oil
                    - 4 eggs, added 1 at a time
                  link: www.cookbooks.com/Recipe-Details.aspx?id=810323
                  site: www.cookbooks.com
                  source: Gathered
                  title: Carrot Cake
      responses:
        '200':
          description: List of recommended recipes
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  time_seconds:
                    type: number
                    format: float
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Recipe'

  /search:
    post:
      summary: Search recipes based on ingredients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngredientSearch'
            examples:
              basicSearch:
                summary: Basic Ingredient Search
                value:
                  ingredients:
                    - flour
                    - soda
                    - cinnamon
                    - salt
                    - eggs
                    - oil
                    - sugar
      responses:
        '200':
          description: List of matching recipes
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  time_seconds:
                    type: number
                    format: float
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Recipe'

  /search/vegetarian:
    post:
      summary: Search vegetarian recipes based on ingredients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngredientSearch'
            examples:
              vegetarianSearch:
                summary: Vegetarian Ingredient Search
                value:
                  ingredients:
                    - flour
                    - soda
                    - cinnamon
                    - salt
                    - eggs
                    - oil
                    - sugar
      responses:
        '200':
          description: List of matching vegetarian recipes
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  time_seconds:
                    type: number
                    format: float
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Recipe'

  /search/vegan:
    post:
      summary: Search vegan recipes based on ingredients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngredientSearch'
            examples:
              veganSearch:
                summary: Vegan Ingredient Search
                value:
                  ingredients:
                    - flour
                    - soda
                    - cinnamon
                    - salt
                    - oil
                    - sugar
      responses:
        '200':
          description: List of matching vegan recipes
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  time_seconds:
                    type: number
                    format: float
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Recipe'

  /search/gluten_free:
    post:
      summary: Search gluten-free recipes based on ingredients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngredientSearch'
            examples:
              glutenFreeSearch:
                summary: Gluten-Free Ingredient Search
                value:
                  ingredients:
                    - flour
                    - soda
                    - cinnamon
                    - salt
                    - eggs
                    - oil
                    - sugar
      responses:
        '200':
          description: List of matching gluten-free recipes
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  time_seconds:
                    type: number
                    format: float
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Recipe'

components:
  schemas:
    Recipe:
      type: object
      properties:
        NER:
          type: array
          items:
            type: string
        directions:
          type: array
          items:
            type: string
        ingredients:
          type: array
          items:
            type: string
        link:
          type: string
        site:
          type: string
        source:
          type: string
        title:
          type: string
    IngredientSearch:
      type: object
      properties:
        ingredients:
          type: array
          items:
            type: string