apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search
        image: europe-docker.pkg.dev/fculcn/search-service/search-service:latest
        ports:
        - containerPort: 5000
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /app/creds.json
        volumeMounts:
        - name: gcp-creds
          mountPath: /app/creds.json
          subPath: creds.json
        resources:
          requests:
            cpu: "500m"
            memory: "1.5Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
      volumes:
      - name: gcp-creds
        secret:
          secretName: gcp-sa-key
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: search-service
  ports:
  - port: 5000
    targetPort: 5000
