apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommend-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommend-service
  template:
    metadata:
      labels:
        app: recommend-service
    spec:
      containers:
      - name: recommend
        image: gcr.io/fculcn/recommend-service:latest
        ports:
        - containerPort: 5000
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /app/creds.json
        volumeMounts:
        - name: gcp-creds
          mountPath: /app/creds.json
          subPath: creds.json
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
      volumes:
      - name: gcp-creds
        secret:
          secretName: gcp-sa-key
---
apiVersion: v1
kind: Service
metadata:
  name: recommend-service
spec:
  selector:
    app: recommend-service
  ports:
  - port: 5000
    targetPort: 5000
