name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: europe-docker.pkg.dev
  CLUSTER_NAME: proj-cluster
  CLUSTER_ZONE: europe-west4
  DEPLOYMENT_NAME: gateway
  IMAGE_NAME: recipe-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/recipe-api:${{ github.sha }} .
          docker push ${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/recipe-api:${{ github.sha }}

      - name: Set GKE context
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} --zone ${{ env.CLUSTER_ZONE }}

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.DEPLOYMENT_NAME }}=${{ env.GAR_LOCATION }}/${{ env.PROJECT_ID }}/recipe-api:${{ github.sha }}

      - name: Run tests
        run: |
          pip install -r requirements.txt
          pytest tests/