name: CI/CD Pipeline for All Services

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: europe-docker.pkg.dev
  CLUSTER_NAME: proj-cluster
  CLUSTER_ZONE: europe-west4
  IMAGE_PREFIX: europe-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Connect to GKE
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE

      - name: Run setup script for all services
        run: |
          chmod +x ./src/setup.sh
          ./src/setup.sh