name: Local DryRun Pipeline

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: europe-docker.pkg.dev
  CLUSTER_NAME: proj-cluster
  CLUSTER_ZONE: europe-west4
  IMAGE_PREFIX: europe-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Connect to GKE
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE

      - name: Create gcp-sa-key secret in Kubernetes
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > key.json
          kubectl create secret generic gcp-sa-key --from-file=key.json=key.json --dry-run=client -o yaml | kubectl apply -f -

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-docker.pkg.dev

      - name: Run deploy setup for all services
        run: |
          chmod +x ./src/dry-run-server.sh
          ./src/dry-run-server.sh
